<?php
namespace Application\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    public function indexAction()
    {
        $data = array(
            'name' => 'John',
            'age'  => 30,
            'city' => 'New York'
        );
        $viewModel = new ViewModel(array('data'=>$data));
        return $viewModel;
    }
}